### ISSUE TITLE
Bug: when printing alignments

### ISSUE THREAD

**Issue by mvences** [iTaxoTools/TaxI2-legacy#11]
Sangeeta encountered a problem when trying to run the program with the "Print alignment" option.

Below is her comment. Please have a look, maybe there is another solution to the problem or a misunderstanding, but I am sure the information below will help you to understand what the problem is.

def print_alignments(sequences, alignment_file):
    sequences = sequences.copy()
    sequences.index = sequences.index.get_level_values('seqid')
    for (seqid_target, target) in sequences.items():
        for (seqid_query, query) in sequences.items():
            print(f"{seqid_target} <-> {seqid_query}", file=alignment_file)
            alignment = aligner.align(target, query)[0]
            print(alignment, file=alignment_file)

should be changed to

def print_alignments(sequences, alignment_file):
    sequences = sequences.copy()
    sequences.index = sequences.index.get_level_values(0)
    for (seqid_target, target) in sequences.items():
        for (seqid_query, query) in sequences.items():
            print(f"{seqid_target} <-> {seqid_query}", file=alignment_file)
            alignment = aligner.align(target, query)[0]
            print(alignment, file=alignment_file)

str input for index.get_level_values retrieves the columns values not the index values.

find below

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.MultiIndex.get_level_values.html
pandas.MultiIndex.get_level_values — pandas 1.2.1 documentation
pandas.MultiIndex.get_level_values¶ MultiIndex.get_level_values (level) [source] ¶ Return vector of label values for requested level. Length of returned vector is equal to the length of the index.
pandas.pydata.org

**Comment by necrosovereign** [comment]
According to the source code of `MultiIndex.get_level_values` and `MultiIndex._get_level_number`, when `name` is a name of a valid level of `index`:
```python
index.get_level_values(name) == index.get_level_values(index.names.index(name))
```
So, there is no reason to make this change. This code should not cause any problems
