### ISSUE TITLE
One more bug in taxi

### ISSUE THREAD

**Issue by mvences** [iTaxoTools/TaxI2-legacy#12]
Again, same thing ... I am here pasting Sangeeta's comments, please review and see if this needs to be fixed and how it can be best done.

def process(self, input_file: str, output_file: str) -> None:
        if self.input_format_name.get() == "Genbank" and self.already_aligned.get():
            raise ValueError(
                "'Already aligned' option is not allowed for the Genbank format.")
        table = self.input_format.load_table(input_file)
        sequences = table.set_index(
            [column for column in table.columns if column != 'sequence'])
        sequences = normalize_sequences(sequences)

should be changed to 

def process(self, input_file: str, output_file: str) -> None:
        if self.input_format_name.get() == "Genbank" and self.already_aligned.get():
            raise ValueError(
                "'Already aligned' option is not allowed for the Genbank format.")
        table = self.input_format.load_table(input_file)
        sequences = table.set_index(
            [column for column in table.columns if column != 'sequence'])
        sequences = normalize_sequences(sequences['sequence'])

last line normalize_sequences want a series not the Dataframe.

**Comment by sangeeta97** [comment]
He used squeeze
