### ISSUE TITLE
Make program specify output directory, not output file(s)

### ISSUE THREAD

**Issue by mvences** [iTaxoTools/TaxI2-legacy#13]
Because we will implement also graphics output in taxi2, the program in the end will output several files. So it will be better to ask the user to specify an output directory rather than an output file name. and then the files will be given default names.

**Comment by necrosovereign** [comment]
What should be the default names?. For now, I will use "taxi2_tables.txt" for the current output file

**Comment by mvences** [comment]
Yes, this is good for now. We can later adjust. I will let you know next week. There will be some more changes in taxi2, but all is coming along very well!
