### ISSUE TITLE
New histograms not working

### ISSUE THREAD

**Issue by mvences** [iTaxoTools/TaxI2-legacy#25]
I was too fast merging this pull request. I have just checked, the new version of Taxi2 does create additional histograms with the appropriate names  ("without inter-genus") but the histograms look identical, still show inter-genus as the other histograms...

**Comment by necrosovereign** [comment]
I didn't think about testing this on files with different genera.

**Comment by necrosovereign** [comment]
By the way, If the pull request doesn't solve the issue, you can reopen it instead of creating a new issue.
