### ISSUE TITLE
Implement simple clustering function in TaxI2

### ISSUE THREAD

**Issue by mvences** [iTaxoTools/TaxI2-legacy#30]
I am opening this issue to make it easier for me and others to track the progress. 

Please add to TaxI2 the clustering function and respective output as in the explanations sent separately by email. Once done, I will think about it and specify the comparisons clusters vs. predefined species that can be added. As a third step, then, the clustering function can in addition become a separate tool.

**Comment by necrosovereign** [comment]
Pandas doesn't have functions for finding the cluster, so it seems that I will have to use the package "networkx"

**Comment by mvences** [comment]
Hmmm, maybe this could be a solution, but I wonder if the problem is not so easy that it could even be coded without specific cluster-finding functions. After all, it is just about going through the matrix of distances and selecting all those sequences that are connected to each other with distances smaller than a certain threshold, in an iterative way until all sequences are assigned to a cluster.
I am fine with using networkx, but please verify that the library is not to heavy, and would allow really  to do this "stupid clustering" described above. Because most clustering algorithms that exist usually apply some more intelligent clustering, trying to optimize centroids and stuff like that which in this very simple implementation we do not want!
For an "intelligent" clustering, the one that probably we would want to implement is this one:
https://github.com/matsengrp/alnclst
which actually gives different options. This one is on my list for later, but at this point it is essential to have the very simple solution.

**Comment by necrosovereign** [comment]
I will use networkx for now and I will think whether there is a clustering algorithm that can be feasibly implemented in Python.

**Comment by mvences** [comment]
I quickly checked the clustering algorithm. The calculation seems to be accurate. I noticed the following small issues that can already be fixed:
1. The numbering of the clusters starts with "Cluster1" in the upper list and with "Cluster0" in the lower list (the one with the distances). It should also in the lower list start with Cluster1 to make numbering consistent.
2. Overall, it seems to me that the clustering takes a very long time. Is there a way for you to check if this is true, i.e., see when running the script how long it takes to generate all other output, and how long then the clustering takes? If indeed the clustering takes very long, maybe there is a way to make it faster?
3. Related to the previous point, it might be useful to make the clustering an optional function. This means, add to the GUI underneath the "Print alignments" the option "Perform clustering" and have it as default not activated. So users could run the program without this time-consuming function (if indeed it is so time consuming as it seems to me).
4. Add a title to the output: "Clustering sequences based on a distance threshold of 0.3 (3%) pairwise uncorrected distance" where the values and the kind of distance used are adapted depending on the selection.
5. Also add then one line saying: "A total of 23 clusters were found, containing between 1 and 8 samples." where the values correspond to those of the clustering result. 

I will try to find the time over the weekend, otherwise on Monday evening, to provide additional instructions.

**Comment by necrosovereign** [comment]
I think that printing the graphs takes the most time
