### ISSUE TITLE
Memory usage improved but still cannot align and process >300 sequences

### ISSUE THREAD

**Issue by mvences** [iTaxoTools/TaxI2-legacy#44]
I have tested the program with different input files, and its performance has distinctly improved. Before, it crashed with >120 sequences while now it is able to process 300 sequences.

It would be good if the program was able to process 400-500 sequence input, and for this you are suggesting to try out Rust. It will pose some challenges probably at the stage of compilation, but these challenges certainly can be overcome. From what I read, Rust is especially good to speed up calculations ... in our case, the problem is not mainly about speed but more about memory usage, so if you think Rust can be helpful for this, please go ahead.

One other important point to check: I tried the program both with input files that were aligned and unaligned. When using the aligned input and checking the box "already aligned" the program still crashed with a memory error, apparently related to pairwise alignment, see screenshot below. Is it possible that disabling the alignment step is not properly working? Assuming that no alignments need to be done, only 500 x 500 comparisons = 250,000 distance values need to be computed which in principle should be no major challenge. Maybe you can look first of all into this. Many other simple programs (for instance MEGA) can easily calculate matrices of genetic distances between 2000 x 2000 sequences within seconds once they are aligned, and probably also 5000 x 5000 sequences (I have not tried). If we can make the program work with large numbers of ALIGNED sequences, say 2000 or 5000, then it is much less problematic that it only can process a maximum of 300 UNALIGNED sequences (the pairwise alignment we are doing is anyway very inefficient, and there are much better multi-alignment alternatives).

![Capture3](https://user-images.githubusercontent.com/66744055/111534143-f236f000-8767-11eb-9b8a-32a613eca0db.PNG)

**Comment by necrosovereign** [comment]
I fixed the mistake that made "Already aligned" option not do anything in #45

**Comment by mvences** [comment]
Indeed, now the program performs well with already aligned input files! Very good. I successfully ran input files with 500, and 1000 sequences, but 2000 were not possible. 

According to the screenshot, here the problem occurs when preparing the distance table, probably the matrix table with many columns. 

Overall, I think it is quite OK if the program has a limit of 300 unaligned and 1000 aligned sequences for the detailed output it is providing now.

However, it would be good if a second analytical route could be implemented for large to very large input files (whether it is fast, with Rust, or not, shouldn't be the biggest concern). 

From the error message below, my (maybe naive) interpretation is that the challenging part is to prepare an array with so many columns and lines to account for all pairwise comparisons. Maybe this can be solved if several of the output items are skipped and the output prepared in an abbreviated format, mostly consisting in the table "summary statistics.txt". Then we can always see which other parts can be derived from this (plotting, clustering). 

In my naive view, I could imagine that in this analytical route, the user needs to define an output folder beforehand where the "summary statistics.txt" is written. Then, the program performs all the pairwise comparisons, and each of them is then consecutively written into this file and then can be removed from the memory. Then, for all the actual statistical analyses, plotting etc., the program would examine again this saved file. This way it should be possible to calculate distances even between extremely large input files with many thousand sequences (only it would take very long, of course). I am thinking about DNAconvert which also is able to convert fastq files of several Gigabyte....
How to implement this in the GUI we need to see, but to start with it could be just a few ugly buttons added somewhere, the user checks a box "simplified analysis for large alignments" and has a browse button for specifying the output folder.




 


![Capture4](https://user-images.githubusercontent.com/66744055/111541484-d7b54480-8770-11eb-8289-2d4b7eac3d10.PNG)

**Comment by mvences** [comment]
Another alternative would also be to write another very simple tool as a kind of "sandbox" to try different ways of calculating and saving pairwise distances from very big input files. Maybe this would be easier than tinkering with TaxI2 which already is a very complex program with many options. So, making a new tool "seqdistcalc" which later we may use or not. With a very simple GUI, just specify one input file (fasta with aligned sequences) and one output file (table with distances), and the program calculates simple uncorrected distances between the inputted sequences and writes the distances in the most efficient way into the table (not in matrix format). 

In this program, you could then try all sorts of things implementing Rust and other things, and I could quickly easily test the performance.  

What do you think? This could be a good way of testing and learning different options, and based on this, decide which direction to take with TaxI2.

**Comment by necrosovereign** [comment]
I replaced the function that aligns and calculate distances between a pair of sequences with a Rust implementation. As a result, there is no significant increase in memory usage during the calculation of distances and the time required for the calculation decreased 3 times.

Should I proceed to prepare a version of the program where pairwise distances are calculated in Rust and collected into the table in Python (I think I can finish this tomorrow), or proceed to implement the calculation of the whole distance table in Rust?

In the second case, what should I do with the Stephanos's code? Should I implement an option to switch between Python implementation and Rust implementation?

**Comment by mvences** [comment]
Yes, I think for now it would be good to keep the "Stefanos solution" available in the code, as a small checkbox "Use pure Python implementation of alignment". Given that we have already discovered unexpected incompatibilities with some of the tools (such as, running on Windows 10 Pro but not Windows 10 Home) this would allow a backup for users if on their specific system the Rust implementation creates problems.

In any case, as you suggested before, we will first exhaustively test the new Code (in this case the Rust implementation) before updating the main branch.
