### ISSUE TITLE
Excessively large distances with "already aligned" sequences

### ISSUE THREAD

**Issue by mvences** [iTaxoTools/TaxI2-legacy#46]
I am currently analyzing a big dataset for which I would like to compute the kind of distance data that TaxI2 is producing. The dataset is already aligned, and I noticed that the program outputs very large distances >0.5 which are unrealistic. I have tested this with a smaller dataset (attached here) and I get the correct distances with maximum values around 0.1 when the program does the alignment, but very large values when I click the "already aligned" option.

The sequences (because they are aligned) contain a number of gaps at the beginning and end. Maybe the program is removing these before starting the distance calculations? Then it would basically compare unaligned sequences. The idea would be to ignore gaps at the beginning and start (which the distance algorithms probably do anyway) but not remove them. Maybe this would solve the problem.

Here below is the example file and the two screenshots.

With aligning sequences in TaxI2, distances are correct:

![Capture_withalignment](https://user-images.githubusercontent.com/66744055/111625146-d32e7180-87ec-11eb-96a5-643232afb374.PNG)

"Already aligned" option, distances are wrong (although sequences are aligned in input file):
![Capture_noalign](https://user-images.githubusercontent.com/66744055/111625343-083ac400-87ed-11eb-9748-9da4869e794c.PNG)

Example file:

[brygootest100seqs.txt](https://github.com/iTaxoTools/TaxI2/files/6163979/brygootest100seqs.txt)

**Comment by necrosovereign** [comment]
All the sequences in the file start with 'n-----'. I don't understand what 'n' signifies in this case. Is it supposed to indicates that the gap in the beginning is not a terminal gap?

**Comment by mvences** [comment]
Aaaah, you are right, I forgot to remove those "n" at the beginning. They were added to avoid artefacts when managing the sequences in Excel. 

HOWEVER, it would be be good in fact if the program treats for the terminal stretches of sequences gaps - missing data n as well as question marks ? as equivalent. So any stretch like  ----- ????? nnnn NNNNN N-????? n------- coming BEFORE or AFTER any other character (ACGTRYSWKM) would be treated equally and excluded from all calculations of distances.

**Comment by necrosovereign** [comment]
What about situations like this:
atgncca
atgtcca
?
Should it be treated as insertion/deletion or replacement? And if it's a replacement, then, for the case of K2P distance, is it transition or transversion? And what if there is '?' instead of 'n'?

**Comment by mvences** [comment]
In this case, both n and ? should be treated as missing information. That is, at this position there could be anything (ACGT-) and for this sequence, the position should not be taken into account.

**Comment by necrosovereign** [comment]
But should it be counted for the p-distance with gaps?

**Comment by mvences** [comment]
No, also for p-distance with gaps, an n or question mark should not be counted.

**Comment by mvences** [comment]
I have just run the program after removing the "n" at the beginning, but it still calculates wrongly the distances, so this was not the origin of the problem.

**Comment by necrosovereign** [comment]
So for such situation
```
gg-ccnccta
ggaccaccaa
```
p-distance should be 1/8 and p-distance with gaps should be 2/9?

**Comment by mvences** [comment]
Yes, correct!
