### ISSUE TITLE
Small issues with new version of TaxI2

### ISSUE THREAD

**Issue by mvences** [iTaxoTools/TaxI2-legacy#61]
So, unfortunately, there are still issues with TaxI2. I am creating here two issues with it. 

This here is the first problem which @necrosovereign you should be able to fix easily I think ... do it next week with a fresh mind. 

For the second problem I will create a second issue and will assign it to @StefanPatman because it is about compilation on a Windows system, and maybe he can solve the problem. 

Issue 1. 

On my Windows10 computer, when I execute the code, most things work well. There are however a few minor issues that originated with the fixes  @necrosovereign applied today:
- When running a fasta file with "all against all" the program terminates with an error "list index out of range". This is new, probably originated when enabling fasta also for the "reference database" mode.
- When running the "against reference database" mode with fasta files, the program executes but produces five output files (rather than just one). There is "Closest rerefence_sequence" but also "Most similar sequence", "Summary statistiocs", and twice the "pairwise uncorrected distance" matrix.

**Comment by necrosovereign** [comment]
The first problem arises from the plotting code, which expects species information. Should the plotting be disabled when the input doesn't contain the species?

I cannot reproduce the second problem. Can you send me the files that cause it?

**Comment by mvences** [comment]
1.  Yes, I would say, your suggestion will be the best for now: just disable plotting (and of course, also disable all matrix tables with values between species etc) when species information in missing (i.e., in fasta input) 

2. For the second problem, in the last compiled version pushed by Stefanos this problem does not show up anymore, so I guess it can be considered as solved.
