### ISSUE TITLE
Problem when compiling TaxI2

### ISSUE THREAD

**Issue by mvences** [iTaxoTools/TaxI2-legacy#62]
I have assigned some minor problems to be fixed by @necrosovereign  in the previous issue.

This one here I assign to @StefanPatman because it is about compilation on Windows.

The  problem we have is that the script version is running fine with tab files on my Windows 10 computer, but on Sangeeta's Windows 10 computer it cannot be executed because it gives an error "seqid specimen_voucher species or organism or sequence column is missing".

The input files used are perfectly fine. As I said, this error shows up (i) on Sangeeta's computer, AND (ii) on the compiled version on my Windows 7 computer. However, it does NOT show up when (iii) I run the compiled version on my Windows 10 computer or (iv) I run the script version on my Windows 10 computer. Also, apparently it does not show up in Linux.

So, to find out what is happening, it would be good if @StefanPatman  you could try compiling this tool on a Windows system. My brain is too tired now to imagine what could be wrong on Sangeeta's computer that prevents a proper compilation, but I would hope that the tool compiles fine on another computer. Maybe wait with this until @necrosovereign has fixed the previous issue, or if you have a few minutes, you could already try now. 

I will be back in the lab on Monday or Tuesday evening and could then do some more exhaustive trials with different compiled versions on different computers.

**Comment by StefanPatman** [comment]
The problem was the Byte Order Mark (BOM) at the beginning of the input files. Under certain conditions it would not be properly ignored, "corrupting" the first column header (seqid). The column names are now restricted to alphanumerical characters, underscores and hyphens, which should clear any problematic invisible characters.

**Comment by mvences** [comment]
Super. The compiled version now works perfectly. I have merged the two pull requests. Great to see you guys work over the weekend.
