### ISSUE TITLE
Bug: "seqid" not found

### ISSUE THREAD

**Issue by mvences** [iTaxoTools/TaxI2-legacy#9]
When running an input file (example attached here) the program gives an error message more or less like "seqid not found".

According to Sangeeta this seems is due to a small bug in the command converting field (column) names to upper vs. lower case and can be easily fixed by changing one command. (she changed "casefold" to "lower" to make it work here, but it will be better if you apply this or an equivalent change in the master version of the code).

The same bug also shows up again when trying to show the alignment output.

[taxi2_short_example_file.zip](https://github.com/iTaxoTools/TaxI2/files/5887430/taxi2_short_example_file.zip)

**Comment by necrosovereign** [comment]
@mvences 
I only get this message when "Print alignments" option is on. I fixed it and it doesn't seem that 'casefold' is a problem.

**Comment by mvences** [comment]
OK. In the next round, I will be checking the performance of taxi2 thoroughly and will then let you know in case the problem shows up again.
